platform :ios, '12.0'
use_frameworks!

target 'craftyDateFormatter_Example' do
  pod 'craftyDateFormatter', :path => '../'

  target 'craftyDateFormatter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
