platform :ios, '12.0'
use_frameworks!

target 'craftyDateFormatter_Example' do
  pod 'craftyDateFormatter', :path => '../'

  target 'craftyDateFormatter_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
