# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/craftyDateFormatter.xcworkspace -scheme craftyDateFormatter-Example -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone SE (2nd generation)' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
